server:
  port: 8888
  
spring:
  application:
    name: smc-config-server
  
  cloud:
    config:
     server:
        git:
          uri: https://github.com/lorenarosessoler/CICE-Proyecto-SharingMyClothes-Config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka